title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              http://onlywangyn.github.io/
signoff:          Nancy
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://onlywangyn.github.io
    external:     true
  - name:         Email
    url:          wangyanan613@hotmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/OnlyWangyn
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
